---
- name: Create EC2 instances
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    image_id: "{{ item.image }}"
    instance_type: "{{ type }}"
    key_name: "{{ key }}"
    security_group: "{{ sg_name }}"
    region: "{{ region_name }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network:
      assign_public_ip: true
      tags:
        environment: "{{ item.name }}"
  loop:
    - { image: "ami-04a81a99f5ec58529", name: "ManagedNode 1"}
    # - { image: "ami-0ae8f15ae66fe8cda"", name: "ManagedNode 2"}

