---
- name: Create EC2 instances
  amazon.aws.ec2_instance:
    name: "{{ item.name }}"
    image_id: "{{ item.image }}"
    instance_type: t2.micro
    key_name: "MyKey"
    security_group: launch-wizard-1
    region: us-east-1
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    network:
      assign_public_ip: true
      tags:
        environment: "{{ item.name }}"
  loop:
    - { image: "ami-04a81a99f5ec58529", name: "ManagedNode 1"}
    # - { image: "ami-0ae8f15ae66fe8cda"", name: "ManagedNode 2"}

